// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./template";
export * from "./templateGroup";
export * from "./templateGroups";
export * from "./templates";

// Import resources to register:
import { Template } from "./template";
import { TemplateGroup } from "./templateGroup";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tctest:Address/template:Template":
                return new Template(name, <any>undefined, { urn })
            case "tctest:Address/templateGroup:TemplateGroup":
                return new TemplateGroup(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tctest", "Address/template", _module)
pulumi.runtime.registerResourceModule("tctest", "Address/templateGroup", _module)
