// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vod

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-tctest/sdk/go/tctest"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "tctest:Vod/adaptiveDynamicStreamingTemplate:AdaptiveDynamicStreamingTemplate":
		r = &AdaptiveDynamicStreamingTemplate{}
	case "tctest:Vod/imageSpriteTemplate:ImageSpriteTemplate":
		r = &ImageSpriteTemplate{}
	case "tctest:Vod/procedureTemplate:ProcedureTemplate":
		r = &ProcedureTemplate{}
	case "tctest:Vod/snapshotByTimeOffsetTemplate:SnapshotByTimeOffsetTemplate":
		r = &SnapshotByTimeOffsetTemplate{}
	case "tctest:Vod/subApplication:SubApplication":
		r = &SubApplication{}
	case "tctest:Vod/superPlayerConfig:SuperPlayerConfig":
		r = &SuperPlayerConfig{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := tctest.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"tctest",
		"Vod/adaptiveDynamicStreamingTemplate",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Vod/imageSpriteTemplate",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Vod/procedureTemplate",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Vod/snapshotByTimeOffsetTemplate",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Vod/subApplication",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Vod/superPlayerConfig",
		&module{version},
	)
}
