// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cls

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-tctest/sdk/go/tctest"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "tctest:Cls/config:Config":
		r = &Config{}
	case "tctest:Cls/configAttachment:ConfigAttachment":
		r = &ConfigAttachment{}
	case "tctest:Cls/configExtra:ConfigExtra":
		r = &ConfigExtra{}
	case "tctest:Cls/cosShipper:CosShipper":
		r = &CosShipper{}
	case "tctest:Cls/logset:Logset":
		r = &Logset{}
	case "tctest:Cls/machineGroup:MachineGroup":
		r = &MachineGroup{}
	case "tctest:Cls/topic:Topic":
		r = &Topic{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := tctest.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"tctest",
		"Cls/config",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cls/configAttachment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cls/configExtra",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cls/cosShipper",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cls/logset",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cls/machineGroup",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cls/topic",
		&module{version},
	)
}
