// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package as

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-tctest/sdk/go/tctest"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "tctest:As/attachment:Attachment":
		r = &Attachment{}
	case "tctest:As/lifecycleHook:LifecycleHook":
		r = &LifecycleHook{}
	case "tctest:As/notification:Notification":
		r = &Notification{}
	case "tctest:As/scalingConfig:ScalingConfig":
		r = &ScalingConfig{}
	case "tctest:As/scalingGroup:ScalingGroup":
		r = &ScalingGroup{}
	case "tctest:As/scalingPolicy:ScalingPolicy":
		r = &ScalingPolicy{}
	case "tctest:As/schedule:Schedule":
		r = &Schedule{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := tctest.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"tctest",
		"As/attachment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"As/lifecycleHook",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"As/notification",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"As/scalingConfig",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"As/scalingGroup",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"As/scalingPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"As/schedule",
		&module{version},
	)
}
