// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vpc

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-tctest/sdk/go/tctest"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "tctest:Vpc/aCL:ACL":
		r = &ACL{}
	case "tctest:Vpc/aclAttachment:AclAttachment":
		r = &AclAttachment{}
	case "tctest:Vpc/instance:Instance":
		r = &Instance{}
	case "tctest:Vpc/routeEntry:RouteEntry":
		r = &RouteEntry{}
	case "tctest:Vpc/routeTable:RouteTable":
		r = &RouteTable{}
	case "tctest:Vpc/subnet:Subnet":
		r = &Subnet{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := tctest.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"tctest",
		"Vpc/aCL",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Vpc/aclAttachment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Vpc/instance",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Vpc/routeEntry",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Vpc/routeTable",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Vpc/subnet",
		&module{version},
	)
}
