// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mysql

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-tctest/sdk/go/tctest"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "tctest:Mysql/account:Account":
		r = &Account{}
	case "tctest:Mysql/accountPrivilege:AccountPrivilege":
		r = &AccountPrivilege{}
	case "tctest:Mysql/backupPolicy:BackupPolicy":
		r = &BackupPolicy{}
	case "tctest:Mysql/instance:Instance":
		r = &Instance{}
	case "tctest:Mysql/privilege:Privilege":
		r = &Privilege{}
	case "tctest:Mysql/readonlyInstance:ReadonlyInstance":
		r = &ReadonlyInstance{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := tctest.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"tctest",
		"Mysql/account",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Mysql/accountPrivilege",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Mysql/backupPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Mysql/instance",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Mysql/privilege",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Mysql/readonlyInstance",
		&module{version},
	)
}
