// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package clb

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-tctest/sdk/go/tctest"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "tctest:Clb/customizedConfig:CustomizedConfig":
		r = &CustomizedConfig{}
	case "tctest:Clb/instance:Instance":
		r = &Instance{}
	case "tctest:Clb/listener:Listener":
		r = &Listener{}
	case "tctest:Clb/listenerRule:ListenerRule":
		r = &ListenerRule{}
	case "tctest:Clb/logSet:LogSet":
		r = &LogSet{}
	case "tctest:Clb/logTopic:LogTopic":
		r = &LogTopic{}
	case "tctest:Clb/redirection:Redirection":
		r = &Redirection{}
	case "tctest:Clb/serverAttachment:ServerAttachment":
		r = &ServerAttachment{}
	case "tctest:Clb/tGAttachmentInstance:TGAttachmentInstance":
		r = &TGAttachmentInstance{}
	case "tctest:Clb/targetGroup:TargetGroup":
		r = &TargetGroup{}
	case "tctest:Clb/targetGroupAttachment:TargetGroupAttachment":
		r = &TargetGroupAttachment{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := tctest.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"tctest",
		"Clb/customizedConfig",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Clb/instance",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Clb/listener",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Clb/listenerRule",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Clb/logSet",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Clb/logTopic",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Clb/redirection",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Clb/serverAttachment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Clb/tGAttachmentInstance",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Clb/targetGroup",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Clb/targetGroupAttachment",
		&module{version},
	)
}
