// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cam

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-tctest/sdk/go/tctest"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "tctest:Cam/group:Group":
		r = &Group{}
	case "tctest:Cam/groupMembership:GroupMembership":
		r = &GroupMembership{}
	case "tctest:Cam/groupPolicyAttachment:GroupPolicyAttachment":
		r = &GroupPolicyAttachment{}
	case "tctest:Cam/oIDCSSO:OIDCSSO":
		r = &OIDCSSO{}
	case "tctest:Cam/policy:Policy":
		r = &Policy{}
	case "tctest:Cam/role:Role":
		r = &Role{}
	case "tctest:Cam/rolePolicyAttachment:RolePolicyAttachment":
		r = &RolePolicyAttachment{}
	case "tctest:Cam/roleSSO:RoleSSO":
		r = &RoleSSO{}
	case "tctest:Cam/sAMLProvider:SAMLProvider":
		r = &SAMLProvider{}
	case "tctest:Cam/user:User":
		r = &User{}
	case "tctest:Cam/userPolicyAttachment:UserPolicyAttachment":
		r = &UserPolicyAttachment{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := tctest.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"tctest",
		"Cam/group",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cam/groupMembership",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cam/groupPolicyAttachment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cam/oIDCSSO",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cam/policy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cam/role",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cam/rolePolicyAttachment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cam/roleSSO",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cam/sAMLProvider",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cam/user",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cam/userPolicyAttachment",
		&module{version},
	)
}
