// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./group";
export * from "./groupLiteRule";
export * from "./groupRule";
export * from "./groups";

// Import resources to register:
import { Group } from "./group";
import { GroupLiteRule } from "./groupLiteRule";
import { GroupRule } from "./groupRule";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tctest:Security/group:Group":
                return new Group(name, <any>undefined, { urn })
            case "tctest:Security/groupLiteRule:GroupLiteRule":
                return new GroupLiteRule(name, <any>undefined, { urn })
            case "tctest:Security/groupRule:GroupRule":
                return new GroupRule(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tctest", "Security/group", _module)
pulumi.runtime.registerResourceModule("tctest", "Security/groupLiteRule", _module)
pulumi.runtime.registerResourceModule("tctest", "Security/groupRule", _module)
