// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./addonAttachment";
export * from "./asScalingGroup";
export * from "./authAttachment";
export * from "./charts";
export * from "./cluster";
export * from "./clusterAttachment";
export * from "./clusterCommonNames";
export * from "./clusterLevels";
export * from "./clusters";
export * from "./nodePool";
export * from "./scaleWorker";

// Import resources to register:
import { AddonAttachment } from "./addonAttachment";
import { AsScalingGroup } from "./asScalingGroup";
import { AuthAttachment } from "./authAttachment";
import { Cluster } from "./cluster";
import { ClusterAttachment } from "./clusterAttachment";
import { NodePool } from "./nodePool";
import { ScaleWorker } from "./scaleWorker";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tctest:Tke/addonAttachment:AddonAttachment":
                return new AddonAttachment(name, <any>undefined, { urn })
            case "tctest:Tke/asScalingGroup:AsScalingGroup":
                return new AsScalingGroup(name, <any>undefined, { urn })
            case "tctest:Tke/authAttachment:AuthAttachment":
                return new AuthAttachment(name, <any>undefined, { urn })
            case "tctest:Tke/cluster:Cluster":
                return new Cluster(name, <any>undefined, { urn })
            case "tctest:Tke/clusterAttachment:ClusterAttachment":
                return new ClusterAttachment(name, <any>undefined, { urn })
            case "tctest:Tke/nodePool:NodePool":
                return new NodePool(name, <any>undefined, { urn })
            case "tctest:Tke/scaleWorker:ScaleWorker":
                return new ScaleWorker(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tctest", "Tke/addonAttachment", _module)
pulumi.runtime.registerResourceModule("tctest", "Tke/asScalingGroup", _module)
pulumi.runtime.registerResourceModule("tctest", "Tke/authAttachment", _module)
pulumi.runtime.registerResourceModule("tctest", "Tke/cluster", _module)
pulumi.runtime.registerResourceModule("tctest", "Tke/clusterAttachment", _module)
pulumi.runtime.registerResourceModule("tctest", "Tke/nodePool", _module)
pulumi.runtime.registerResourceModule("tctest", "Tke/scaleWorker", _module)
