// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tctest.User
{
    public static class Info
    {
        public static Task<InfoResult> InvokeAsync(InfoArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<InfoResult>("tctest:User/info:Info", args ?? new InfoArgs(), options.WithDefaults());

        public static Output<InfoResult> Invoke(InfoInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<InfoResult>("tctest:User/info:Info", args ?? new InfoInvokeArgs(), options.WithDefaults());
    }


    public sealed class InfoArgs : Pulumi.InvokeArgs
    {
        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        public InfoArgs()
        {
        }
    }

    public sealed class InfoInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        public InfoInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class InfoResult
    {
        public readonly string AppId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string OwnerUin;
        public readonly string? ResultOutputFile;
        public readonly string Uin;

        [OutputConstructor]
        private InfoResult(
            string appId,

            string id,

            string ownerUin,

            string? resultOutputFile,

            string uin)
        {
            AppId = appId;
            Id = id;
            OwnerUin = ownerUin;
            ResultOutputFile = resultOutputFile;
            Uin = uin;
        }
    }
}
