// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./externalKey";
export * from "./keys";
export * from "./kmsKey";

// Import resources to register:
import { ExternalKey } from "./externalKey";
import { KmsKey } from "./kmsKey";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tctest:Kms/externalKey:ExternalKey":
                return new ExternalKey(name, <any>undefined, { urn })
            case "tctest:Kms/kmsKey:KmsKey":
                return new KmsKey(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tctest", "Kms/externalKey", _module)
pulumi.runtime.registerResourceModule("tctest", "Kms/kmsKey", _module)
