// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./alarmPolicy";
export * from "./bindingAlarmReceiver";
export * from "./bindingObject";
export * from "./bindingObjects";
export * from "./data";
export * from "./policyBindingObject";
export * from "./policyConditions";
export * from "./policyGroup";
export * from "./policyGroups";
export * from "./productEvent";
export * from "./productNamespace";

// Import resources to register:
import { AlarmPolicy } from "./alarmPolicy";
import { BindingAlarmReceiver } from "./bindingAlarmReceiver";
import { BindingObject } from "./bindingObject";
import { PolicyBindingObject } from "./policyBindingObject";
import { PolicyGroup } from "./policyGroup";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tctest:Monitor/alarmPolicy:AlarmPolicy":
                return new AlarmPolicy(name, <any>undefined, { urn })
            case "tctest:Monitor/bindingAlarmReceiver:BindingAlarmReceiver":
                return new BindingAlarmReceiver(name, <any>undefined, { urn })
            case "tctest:Monitor/bindingObject:BindingObject":
                return new BindingObject(name, <any>undefined, { urn })
            case "tctest:Monitor/policyBindingObject:PolicyBindingObject":
                return new PolicyBindingObject(name, <any>undefined, { urn })
            case "tctest:Monitor/policyGroup:PolicyGroup":
                return new PolicyGroup(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tctest", "Monitor/alarmPolicy", _module)
pulumi.runtime.registerResourceModule("tctest", "Monitor/bindingAlarmReceiver", _module)
pulumi.runtime.registerResourceModule("tctest", "Monitor/bindingObject", _module)
pulumi.runtime.registerResourceModule("tctest", "Monitor/policyBindingObject", _module)
pulumi.runtime.registerResourceModule("tctest", "Monitor/policyGroup", _module)
