// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cbs

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-tctest/sdk/go/tctest"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "tctest:Cbs/snapshot:Snapshot":
		r = &Snapshot{}
	case "tctest:Cbs/snapshotPolicy:SnapshotPolicy":
		r = &SnapshotPolicy{}
	case "tctest:Cbs/snapshotPolicyAttachment:SnapshotPolicyAttachment":
		r = &SnapshotPolicyAttachment{}
	case "tctest:Cbs/storage:Storage":
		r = &Storage{}
	case "tctest:Cbs/storageAttachment:StorageAttachment":
		r = &StorageAttachment{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := tctest.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"tctest",
		"Cbs/snapshot",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cbs/snapshotPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cbs/snapshotPolicyAttachment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cbs/storage",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Cbs/storageAttachment",
		&module{version},
	)
}
