// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sqlserver

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-tctest/sdk/go/tctest"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "tctest:Sqlserver/account:Account":
		r = &Account{}
	case "tctest:Sqlserver/accountDBAttachment:AccountDBAttachment":
		r = &AccountDBAttachment{}
	case "tctest:Sqlserver/basicInstance:BasicInstance":
		r = &BasicInstance{}
	case "tctest:Sqlserver/dB:DB":
		r = &DB{}
	case "tctest:Sqlserver/instance:Instance":
		r = &Instance{}
	case "tctest:Sqlserver/publishSubscribe:PublishSubscribe":
		r = &PublishSubscribe{}
	case "tctest:Sqlserver/readonlyInstance:ReadonlyInstance":
		r = &ReadonlyInstance{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := tctest.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"tctest",
		"Sqlserver/account",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Sqlserver/accountDBAttachment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Sqlserver/basicInstance",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Sqlserver/dB",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Sqlserver/instance",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Sqlserver/publishSubscribe",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Sqlserver/readonlyInstance",
		&module{version},
	)
}
