// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package apigateway

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-tctest/sdk/go/tctest"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "tctest:APIGateway/aPI:API":
		r = &API{}
	case "tctest:APIGateway/aPIKey:APIKey":
		r = &APIKey{}
	case "tctest:APIGateway/aPIKeyAttachment:APIKeyAttachment":
		r = &APIKeyAttachment{}
	case "tctest:APIGateway/customDomain:CustomDomain":
		r = &CustomDomain{}
	case "tctest:APIGateway/iPStrategy:IPStrategy":
		r = &IPStrategy{}
	case "tctest:APIGateway/service:Service":
		r = &Service{}
	case "tctest:APIGateway/serviceRelease:ServiceRelease":
		r = &ServiceRelease{}
	case "tctest:APIGateway/strategyAttachment:StrategyAttachment":
		r = &StrategyAttachment{}
	case "tctest:APIGateway/usagePlan:UsagePlan":
		r = &UsagePlan{}
	case "tctest:APIGateway/usagePlanAttachment:UsagePlanAttachment":
		r = &UsagePlanAttachment{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := tctest.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"tctest",
		"APIGateway/aPI",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"APIGateway/aPIKey",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"APIGateway/aPIKeyAttachment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"APIGateway/customDomain",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"APIGateway/iPStrategy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"APIGateway/service",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"APIGateway/serviceRelease",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"APIGateway/strategyAttachment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"APIGateway/usagePlan",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"APIGateway/usagePlanAttachment",
		&module{version},
	)
}
