// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./account";
export * from "./accountDBAttachment";
export * from "./accountDBAttachments";
export * from "./accounts";
export * from "./backups";
export * from "./basicInstance";
export * from "./basicInstances";
export * from "./db";
export * from "./dbs";
export * from "./instance";
export * from "./instances";
export * from "./publishSubscribe";
export * from "./publishSubscribes";
export * from "./readonlyGroups";
export * from "./readonlyInstance";
export * from "./zoneConfig";

// Import resources to register:
import { Account } from "./account";
import { AccountDBAttachment } from "./accountDBAttachment";
import { BasicInstance } from "./basicInstance";
import { DB } from "./db";
import { Instance } from "./instance";
import { PublishSubscribe } from "./publishSubscribe";
import { ReadonlyInstance } from "./readonlyInstance";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tctest:Sqlserver/account:Account":
                return new Account(name, <any>undefined, { urn })
            case "tctest:Sqlserver/accountDBAttachment:AccountDBAttachment":
                return new AccountDBAttachment(name, <any>undefined, { urn })
            case "tctest:Sqlserver/basicInstance:BasicInstance":
                return new BasicInstance(name, <any>undefined, { urn })
            case "tctest:Sqlserver/dB:DB":
                return new DB(name, <any>undefined, { urn })
            case "tctest:Sqlserver/instance:Instance":
                return new Instance(name, <any>undefined, { urn })
            case "tctest:Sqlserver/publishSubscribe:PublishSubscribe":
                return new PublishSubscribe(name, <any>undefined, { urn })
            case "tctest:Sqlserver/readonlyInstance:ReadonlyInstance":
                return new ReadonlyInstance(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tctest", "Sqlserver/account", _module)
pulumi.runtime.registerResourceModule("tctest", "Sqlserver/accountDBAttachment", _module)
pulumi.runtime.registerResourceModule("tctest", "Sqlserver/basicInstance", _module)
pulumi.runtime.registerResourceModule("tctest", "Sqlserver/dB", _module)
pulumi.runtime.registerResourceModule("tctest", "Sqlserver/instance", _module)
pulumi.runtime.registerResourceModule("tctest", "Sqlserver/publishSubscribe", _module)
pulumi.runtime.registerResourceModule("tctest", "Sqlserver/readonlyInstance", _module)
