// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./customizedConfig";
export * from "./instance";
export * from "./instances";
export * from "./listener";
export * from "./listenerRule";
export * from "./listenerRules";
export * from "./listeners";
export * from "./logSet";
export * from "./logTopic";
export * from "./redirection";
export * from "./redirections";
export * from "./serverAttachment";
export * from "./serverAttachments";
export * from "./targetGroup";
export * from "./targetGroupAttachment";
export * from "./targetGroups";
export * from "./tgattachmentInstance";

// Import resources to register:
import { CustomizedConfig } from "./customizedConfig";
import { Instance } from "./instance";
import { Listener } from "./listener";
import { ListenerRule } from "./listenerRule";
import { LogSet } from "./logSet";
import { LogTopic } from "./logTopic";
import { Redirection } from "./redirection";
import { ServerAttachment } from "./serverAttachment";
import { TGAttachmentInstance } from "./tgattachmentInstance";
import { TargetGroup } from "./targetGroup";
import { TargetGroupAttachment } from "./targetGroupAttachment";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tctest:Clb/customizedConfig:CustomizedConfig":
                return new CustomizedConfig(name, <any>undefined, { urn })
            case "tctest:Clb/instance:Instance":
                return new Instance(name, <any>undefined, { urn })
            case "tctest:Clb/listener:Listener":
                return new Listener(name, <any>undefined, { urn })
            case "tctest:Clb/listenerRule:ListenerRule":
                return new ListenerRule(name, <any>undefined, { urn })
            case "tctest:Clb/logSet:LogSet":
                return new LogSet(name, <any>undefined, { urn })
            case "tctest:Clb/logTopic:LogTopic":
                return new LogTopic(name, <any>undefined, { urn })
            case "tctest:Clb/redirection:Redirection":
                return new Redirection(name, <any>undefined, { urn })
            case "tctest:Clb/serverAttachment:ServerAttachment":
                return new ServerAttachment(name, <any>undefined, { urn })
            case "tctest:Clb/tGAttachmentInstance:TGAttachmentInstance":
                return new TGAttachmentInstance(name, <any>undefined, { urn })
            case "tctest:Clb/targetGroup:TargetGroup":
                return new TargetGroup(name, <any>undefined, { urn })
            case "tctest:Clb/targetGroupAttachment:TargetGroupAttachment":
                return new TargetGroupAttachment(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tctest", "Clb/customizedConfig", _module)
pulumi.runtime.registerResourceModule("tctest", "Clb/instance", _module)
pulumi.runtime.registerResourceModule("tctest", "Clb/listener", _module)
pulumi.runtime.registerResourceModule("tctest", "Clb/listenerRule", _module)
pulumi.runtime.registerResourceModule("tctest", "Clb/logSet", _module)
pulumi.runtime.registerResourceModule("tctest", "Clb/logTopic", _module)
pulumi.runtime.registerResourceModule("tctest", "Clb/redirection", _module)
pulumi.runtime.registerResourceModule("tctest", "Clb/serverAttachment", _module)
pulumi.runtime.registerResourceModule("tctest", "Clb/tGAttachmentInstance", _module)
pulumi.runtime.registerResourceModule("tctest", "Clb/targetGroup", _module)
pulumi.runtime.registerResourceModule("tctest", "Clb/targetGroupAttachment", _module)
