// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./api";
export * from "./apikey";
export * from "./apikeyAttachment";
export * from "./customDomain";
export * from "./ipstrategy";
export * from "./service";
export * from "./serviceRelease";
export * from "./strategyAttachment";
export * from "./usagePlan";
export * from "./usagePlanAttachment";

// Import resources to register:
import { API } from "./api";
import { APIKey } from "./apikey";
import { APIKeyAttachment } from "./apikeyAttachment";
import { CustomDomain } from "./customDomain";
import { IPStrategy } from "./ipstrategy";
import { Service } from "./service";
import { ServiceRelease } from "./serviceRelease";
import { StrategyAttachment } from "./strategyAttachment";
import { UsagePlan } from "./usagePlan";
import { UsagePlanAttachment } from "./usagePlanAttachment";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tctest:APIGateway/aPI:API":
                return new API(name, <any>undefined, { urn })
            case "tctest:APIGateway/aPIKey:APIKey":
                return new APIKey(name, <any>undefined, { urn })
            case "tctest:APIGateway/aPIKeyAttachment:APIKeyAttachment":
                return new APIKeyAttachment(name, <any>undefined, { urn })
            case "tctest:APIGateway/customDomain:CustomDomain":
                return new CustomDomain(name, <any>undefined, { urn })
            case "tctest:APIGateway/iPStrategy:IPStrategy":
                return new IPStrategy(name, <any>undefined, { urn })
            case "tctest:APIGateway/service:Service":
                return new Service(name, <any>undefined, { urn })
            case "tctest:APIGateway/serviceRelease:ServiceRelease":
                return new ServiceRelease(name, <any>undefined, { urn })
            case "tctest:APIGateway/strategyAttachment:StrategyAttachment":
                return new StrategyAttachment(name, <any>undefined, { urn })
            case "tctest:APIGateway/usagePlan:UsagePlan":
                return new UsagePlan(name, <any>undefined, { urn })
            case "tctest:APIGateway/usagePlanAttachment:UsagePlanAttachment":
                return new UsagePlanAttachment(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tctest", "APIGateway/aPI", _module)
pulumi.runtime.registerResourceModule("tctest", "APIGateway/aPIKey", _module)
pulumi.runtime.registerResourceModule("tctest", "APIGateway/aPIKeyAttachment", _module)
pulumi.runtime.registerResourceModule("tctest", "APIGateway/customDomain", _module)
pulumi.runtime.registerResourceModule("tctest", "APIGateway/iPStrategy", _module)
pulumi.runtime.registerResourceModule("tctest", "APIGateway/service", _module)
pulumi.runtime.registerResourceModule("tctest", "APIGateway/serviceRelease", _module)
pulumi.runtime.registerResourceModule("tctest", "APIGateway/strategyAttachment", _module)
pulumi.runtime.registerResourceModule("tctest", "APIGateway/usagePlan", _module)
pulumi.runtime.registerResourceModule("tctest", "APIGateway/usagePlanAttachment", _module)
