// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./instance";
export * from "./namespace";
export * from "./namespaceRoleAttachment";
export * from "./role";
export * from "./topic";

// Import resources to register:
import { Instance } from "./instance";
import { Namespace } from "./namespace";
import { NamespaceRoleAttachment } from "./namespaceRoleAttachment";
import { Role } from "./role";
import { Topic } from "./topic";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tctest:Tdmq/instance:Instance":
                return new Instance(name, <any>undefined, { urn })
            case "tctest:Tdmq/namespace:Namespace":
                return new Namespace(name, <any>undefined, { urn })
            case "tctest:Tdmq/namespaceRoleAttachment:NamespaceRoleAttachment":
                return new NamespaceRoleAttachment(name, <any>undefined, { urn })
            case "tctest:Tdmq/role:Role":
                return new Role(name, <any>undefined, { urn })
            case "tctest:Tdmq/topic:Topic":
                return new Topic(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tctest", "Tdmq/instance", _module)
pulumi.runtime.registerResourceModule("tctest", "Tdmq/namespace", _module)
pulumi.runtime.registerResourceModule("tctest", "Tdmq/namespaceRoleAttachment", _module)
pulumi.runtime.registerResourceModule("tctest", "Tdmq/role", _module)
pulumi.runtime.registerResourceModule("tctest", "Tdmq/topic", _module)
