// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package gaap

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-tctest/sdk/go/tctest"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "tctest:Gaap/certificate:Certificate":
		r = &Certificate{}
	case "tctest:Gaap/domainErrorPageInfo:DomainErrorPageInfo":
		r = &DomainErrorPageInfo{}
	case "tctest:Gaap/httpDomain:HttpDomain":
		r = &HttpDomain{}
	case "tctest:Gaap/httpRule:HttpRule":
		r = &HttpRule{}
	case "tctest:Gaap/layer4Listener:Layer4Listener":
		r = &Layer4Listener{}
	case "tctest:Gaap/layer7Listener:Layer7Listener":
		r = &Layer7Listener{}
	case "tctest:Gaap/proxy:Proxy":
		r = &Proxy{}
	case "tctest:Gaap/realserver:Realserver":
		r = &Realserver{}
	case "tctest:Gaap/securityPolicy:SecurityPolicy":
		r = &SecurityPolicy{}
	case "tctest:Gaap/securityRule:SecurityRule":
		r = &SecurityRule{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := tctest.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"tctest",
		"Gaap/certificate",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Gaap/domainErrorPageInfo",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Gaap/httpDomain",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Gaap/httpRule",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Gaap/layer4Listener",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Gaap/layer7Listener",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Gaap/proxy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Gaap/realserver",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Gaap/securityPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Gaap/securityRule",
		&module{version},
	)
}
