// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./attachment";
export * from "./lifecycleHook";
export * from "./notification";
export * from "./scalingConfig";
export * from "./scalingConfigs";
export * from "./scalingGroup";
export * from "./scalingGroups";
export * from "./scalingPolicies";
export * from "./scalingPolicy";
export * from "./schedule";

// Import resources to register:
import { Attachment } from "./attachment";
import { LifecycleHook } from "./lifecycleHook";
import { Notification } from "./notification";
import { ScalingConfig } from "./scalingConfig";
import { ScalingGroup } from "./scalingGroup";
import { ScalingPolicy } from "./scalingPolicy";
import { Schedule } from "./schedule";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tctest:As/attachment:Attachment":
                return new Attachment(name, <any>undefined, { urn })
            case "tctest:As/lifecycleHook:LifecycleHook":
                return new LifecycleHook(name, <any>undefined, { urn })
            case "tctest:As/notification:Notification":
                return new Notification(name, <any>undefined, { urn })
            case "tctest:As/scalingConfig:ScalingConfig":
                return new ScalingConfig(name, <any>undefined, { urn })
            case "tctest:As/scalingGroup:ScalingGroup":
                return new ScalingGroup(name, <any>undefined, { urn })
            case "tctest:As/scalingPolicy:ScalingPolicy":
                return new ScalingPolicy(name, <any>undefined, { urn })
            case "tctest:As/schedule:Schedule":
                return new Schedule(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tctest", "As/attachment", _module)
pulumi.runtime.registerResourceModule("tctest", "As/lifecycleHook", _module)
pulumi.runtime.registerResourceModule("tctest", "As/notification", _module)
pulumi.runtime.registerResourceModule("tctest", "As/scalingConfig", _module)
pulumi.runtime.registerResourceModule("tctest", "As/scalingGroup", _module)
pulumi.runtime.registerResourceModule("tctest", "As/scalingPolicy", _module)
pulumi.runtime.registerResourceModule("tctest", "As/schedule", _module)
