// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package tcr

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-tctest/sdk/go/tctest"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "tctest:Tcr/instance:Instance":
		r = &Instance{}
	case "tctest:Tcr/namespace:Namespace":
		r = &Namespace{}
	case "tctest:Tcr/repository:Repository":
		r = &Repository{}
	case "tctest:Tcr/tcrToken:TcrToken":
		r = &TcrToken{}
	case "tctest:Tcr/vpcAttachment:VpcAttachment":
		r = &VpcAttachment{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := tctest.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"tctest",
		"Tcr/instance",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Tcr/namespace",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Tcr/repository",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Tcr/tcrToken",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Tcr/vpcAttachment",
		&module{version},
	)
}
