// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package tdmq

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-tctest/sdk/go/tctest"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "tctest:Tdmq/instance:Instance":
		r = &Instance{}
	case "tctest:Tdmq/namespace:Namespace":
		r = &Namespace{}
	case "tctest:Tdmq/namespaceRoleAttachment:NamespaceRoleAttachment":
		r = &NamespaceRoleAttachment{}
	case "tctest:Tdmq/role:Role":
		r = &Role{}
	case "tctest:Tdmq/topic:Topic":
		r = &Topic{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := tctest.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"tctest",
		"Tdmq/instance",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Tdmq/namespace",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Tdmq/namespaceRoleAttachment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Tdmq/role",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"tctest",
		"Tdmq/topic",
		&module{version},
	)
}
