// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./acl";
export * from "./aclAttachment";
export * from "./acls";
export * from "./instance";
export * from "./instances";
export * from "./routeEntry";
export * from "./routeTable";
export * from "./routeTables";
export * from "./subnet";
export * from "./subnets";
export * from "./vpcInstances";

// Import resources to register:
import { ACL } from "./acl";
import { AclAttachment } from "./aclAttachment";
import { Instance } from "./instance";
import { RouteEntry } from "./routeEntry";
import { RouteTable } from "./routeTable";
import { Subnet } from "./subnet";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tctest:Vpc/aCL:ACL":
                return new ACL(name, <any>undefined, { urn })
            case "tctest:Vpc/aclAttachment:AclAttachment":
                return new AclAttachment(name, <any>undefined, { urn })
            case "tctest:Vpc/instance:Instance":
                return new Instance(name, <any>undefined, { urn })
            case "tctest:Vpc/routeEntry:RouteEntry":
                return new RouteEntry(name, <any>undefined, { urn })
            case "tctest:Vpc/routeTable:RouteTable":
                return new RouteTable(name, <any>undefined, { urn })
            case "tctest:Vpc/subnet:Subnet":
                return new Subnet(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tctest", "Vpc/aCL", _module)
pulumi.runtime.registerResourceModule("tctest", "Vpc/aclAttachment", _module)
pulumi.runtime.registerResourceModule("tctest", "Vpc/instance", _module)
pulumi.runtime.registerResourceModule("tctest", "Vpc/routeEntry", _module)
pulumi.runtime.registerResourceModule("tctest", "Vpc/routeTable", _module)
pulumi.runtime.registerResourceModule("tctest", "Vpc/subnet", _module)
