// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./connection";
export * from "./connections";
export * from "./customerGateway";
export * from "./customerGateways";
export * from "./gateway";
export * from "./gatewayRoute";
export * from "./gatewayRoutes";
export * from "./gateways";
export * from "./sslClient";
export * from "./sslServer";

// Import resources to register:
import { Connection } from "./connection";
import { CustomerGateway } from "./customerGateway";
import { Gateway } from "./gateway";
import { GatewayRoute } from "./gatewayRoute";
import { SslClient } from "./sslClient";
import { SslServer } from "./sslServer";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tctest:Vpn/connection:Connection":
                return new Connection(name, <any>undefined, { urn })
            case "tctest:Vpn/customerGateway:CustomerGateway":
                return new CustomerGateway(name, <any>undefined, { urn })
            case "tctest:Vpn/gateway:Gateway":
                return new Gateway(name, <any>undefined, { urn })
            case "tctest:Vpn/gatewayRoute:GatewayRoute":
                return new GatewayRoute(name, <any>undefined, { urn })
            case "tctest:Vpn/sslClient:SslClient":
                return new SslClient(name, <any>undefined, { urn })
            case "tctest:Vpn/sslServer:SslServer":
                return new SslServer(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tctest", "Vpn/connection", _module)
pulumi.runtime.registerResourceModule("tctest", "Vpn/customerGateway", _module)
pulumi.runtime.registerResourceModule("tctest", "Vpn/gateway", _module)
pulumi.runtime.registerResourceModule("tctest", "Vpn/gatewayRoute", _module)
pulumi.runtime.registerResourceModule("tctest", "Vpn/sslClient", _module)
pulumi.runtime.registerResourceModule("tctest", "Vpn/sslServer", _module)
