// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./images";
export * from "./instance";
export * from "./instancesTypes";
export * from "./reservedInstance";
export * from "./reservedInstanceConfigs";

// Import resources to register:
import { Instance } from "./instance";
import { ReservedInstance } from "./reservedInstance";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tctest:Cvm/instance:Instance":
                return new Instance(name, <any>undefined, { urn })
            case "tctest:Cvm/reservedInstance:ReservedInstance":
                return new ReservedInstance(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tctest", "Cvm/instance", _module)
pulumi.runtime.registerResourceModule("tctest", "Cvm/reservedInstance", _module)
